version: '3.8'

networks:
  zabx_net:
  grafana_net:
  prometheus_network:
  influxdb_network:

volumes:
prometheus_data:

services:
    grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
volumes:
  grafana-storage: {}


#prometheus
#zabbix